name: solx
description: Solx App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  unity_ads_plugin: ^0.3.30

flutter:
  uses-material-design: true
